AllCops:
  TargetRubyVersion: 3.3.0

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Max: 20
