AllCops:
  TargetRubyVersion: 3.3.0

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15
Layout/TrailingEmptyLines:
  Enabled: false
